
interface SoilData {
  location: string;
  soilType: string;
  ph: number;
  texture: {
    sand: number;
    silt: number;
    clay: number;
  };
  organicMatter: number;
  nutrients: {
    nitrogen: number;
    phosphorus: number;
    potassium: number;
    calcium: number;
    magnesium: number;
    sulfur: number;
  };
  cec: number;
}

export const generateSoilReport = (data: SoilData): string => {
  const report = `
SOIL ANALYSIS REPORT
===================

Location: ${data.location}
Date: ${new Date().toLocaleDateString()}

GENERAL CHARACTERISTICS
---------------------
Soil Type: ${data.soilType}
pH Level: ${data.ph} (${data.ph < 6.5 ? "Acidic" : data.ph > 7.5 ? "Alkaline" : "Neutral"})
Organic Matter: ${data.organicMatter}%
CEC: ${data.cec} meq/100g

SOIL TEXTURE
-----------
Sand: ${data.texture.sand}%
Silt: ${data.texture.silt}%
Clay: ${data.texture.clay}%

NUTRIENT ANALYSIS
---------------
Nitrogen (N): ${data.nutrients.nitrogen} ppm
Phosphorus (P): ${data.nutrients.phosphorus} ppm
Potassium (K): ${data.nutrients.potassium} ppm
Calcium (Ca): ${data.nutrients.calcium} ppm
Magnesium (Mg): ${data.nutrients.magnesium} ppm
Sulfur (S): ${data.nutrients.sulfur} ppm

RECOMMENDATIONS
-------------
1. ${data.ph < 6.5 ? "Consider liming to raise pH" : data.ph > 7.5 ? "Consider adding sulfur to lower pH" : "Maintain current pH management practices"}
2. ${data.organicMatter < 3 ? "Increase organic matter through cover cropping or compost application" : "Maintain current organic matter levels"}
3. Focus on balanced nutrient management based on specific crop needs

Generated by FarmAI Soil Analysis System
`;
  return report;
};

export const downloadReport = (data: SoilData) => {
  const report = generateSoilReport(data);
  const blob = new Blob([report], { type: 'text/plain' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `soil-report-${data.location.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};

